### ISSUE TITLE
undefined method `payload' for Mongo::Protocol::Query

### ISSUE THREAD

**Issue by coin8086** [MiniProfiler/rack-mini-profiler#223]
I encountered the problem in my Sinatra App with MongoDB and the profiler on:

2016-03-23 23:24:26 - NoMethodError - undefined method `payload' for #Mongo::Protocol::Query:0x00000003356cb0:

/home/robert/.rvm/gems/ruby-2.2.1/gems/rack-mini-profiler-0.9.9.2/lib/patches/db/mongo.rb:6:in `dispatch_with_timing'

When I turn off the profiler it's all right. My MongoDB version is 3.0 and Ruby Mongo Driver is 2.0. 

I saw that #156 also addressed the payload method. It seems that the payload method is gone now.

**Comment by kbrock** [comment]
Looks like [payload] was implemented for ruby mongo driver version 2.1 per [gem](https://github.com/mongodb/mongo-ruby-driver/blob/3d8f27fd689e01be409b52539f716fab987a7c19/lib/mongo/protocol/query.rb#L80)

Are you able to upgrade to 2.1 and check this out?

**Comment by coin8086** [comment]
@kbrock OK, let me try it out. Thanks for your tips!

**Comment by coin8086** [comment]
@kbrock Yes, it works after I upgraded the Mongo Ruby Driver to 2.2(I guess 2.1 also works). Thanks a lot!
